#!/usr/bin/env node
// protect-files: refuse Edit/Write to three classes of file that are never hand-authored.
// Portable version of an earlier repo-local hook that encoded the same three rules in
// Rust spellings (*.lock, */target/*).
//
//   1. secrets      - .env and friends. The load-bearing one: the failure mode is a
//                     credential in a diff. `.env.example` and its siblings are templates
//                     with no secrets in them, and are exactly the file you want to edit
//                     when documenting configuration, so they are exempt.
//   2. lockfiles    - generated by a resolver from a manifest. Editing one by hand produces
//                     a lockfile that disagrees with the resolver, which surfaces later as
//                     an unreproducible build.
//   3. build output - target/, node_modules/, dist/ and friends. Writes here are always a
//                     mistake or a path bug; the next build erases them either way.
//
// PreToolUse protocol: read tool call JSON on stdin, deny via hookSpecificOutput JSON.
// Same posture as git-guard: a guardrail against the unattended mistake, not a security
// boundary. It reads tool_input.file_path, so a heredoc through Bash is not caught.

import { protectedFileReason } from '../../lib/hook-policy.mjs'
import { preToolDeny } from './wire.mjs'

const deny = (reason) => {
  process.stdout.write(JSON.stringify(preToolDeny(reason)))
  process.exit(0)
}

let raw = ''
process.stdin.on('data', (c) => (raw += c))
process.stdin.on('end', () => {
  let file = ''
  try {
    file = JSON.parse(raw)?.tool_input?.file_path || ''
  } catch {
    process.exit(0) // unparseable input is the harness's problem, not a policy breach
  }
  if (!file) process.exit(0)

  const reason = protectedFileReason(file)
  if (reason) deny(reason)

  process.exit(0)
})
