#!/usr/bin/env node
// protect-files: refuse Edit/Write to four classes of file that are never tool-authored.
// Portable version of an earlier repo-local hook that encoded the secrets, lockfile and
// build-output rules in Rust spellings (*.lock, */target/*).
//
//   1. secrets      - .env and friends. The load-bearing one: the failure mode is a
//                     credential in a diff. `.env.example` and its siblings are templates
//                     with no secrets in them, and are exactly the file you want to edit
//                     when documenting configuration, so they are exempt.
//   2. .flow/managed - the committed marker that opts a repository into flow's merge
//                     guardrail. A tool call that could edit or delete it could opt the
//                     repository out of its own guardrail, so a human commit changes it.
//   3. lockfiles    - generated by a resolver from a manifest. Editing one by hand produces
//                     a lockfile that disagrees with the resolver, which surfaces later as
//                     an unreproducible build.
//   4. build output - target/, node_modules/, dist/ and friends. Writes here are always a
//                     mistake or a path bug; the next build erases them either way.
//
// PreToolUse protocol: read tool call JSON on stdin, deny via hookSpecificOutput JSON.
// Same posture as git-guard: a guardrail against the unattended mistake, not a security
// boundary. It reads the path the tool names - `file_path` for Edit and Write,
// `notebook_path` for NotebookEdit - so a heredoc through Bash is not caught.

import { protectedFileReason } from '../../lib/hook-policy.mjs'
import { preToolDeny } from './wire.mjs'

const deny = (reason) => {
  process.stdout.write(JSON.stringify(preToolDeny(reason)))
  process.exit(0)
}

let raw = ''
process.stdin.on('data', (c) => (raw += c))
process.stdin.on('end', () => {
  let file = ''
  try {
    // hooks.json matches Edit|Write|NotebookEdit, and NotebookEdit names its target
    // `notebook_path`. Reading file_path alone let every notebook write through.
    const toolInput = JSON.parse(raw)?.tool_input
    file = toolInput?.file_path || toolInput?.notebook_path || ''
  } catch {
    process.exit(0) // unparseable input is the harness's problem, not a policy breach
  }
  if (!file) process.exit(0)

  const reason = protectedFileReason(file)
  if (reason) deny(reason)

  process.exit(0)
})
