#!/usr/bin/env node
// protect-files: refuse Edit/Write to three classes of file that are never hand-authored.
// Portable version of trawl/.claude/hooks/protect-files.sh, which encoded the same three
// rules in Rust spellings (*.lock, */target/*).
//
//   1. secrets      — .env and friends. The load-bearing one: the failure mode is a
//                     credential in a diff. `.env.example` and its siblings are templates
//                     with no secrets in them, and are exactly the file you want to edit
//                     when documenting configuration, so they are exempt.
//   2. lockfiles    — generated by a resolver from a manifest. Editing one by hand produces
//                     a lockfile that disagrees with the resolver, which surfaces later as
//                     an unreproducible build.
//   3. build output — target/, node_modules/, dist/ and friends. Writes here are always a
//                     mistake or a path bug; the next build erases them either way.
//
// PreToolUse protocol: read tool call JSON on stdin, deny via hookSpecificOutput JSON.
// Same posture as git-guard: a guardrail against the unattended mistake, not a security
// boundary. It reads tool_input.file_path, so a heredoc through Bash is not caught.

const SECRET = /(^|\/)\.env(\.[A-Za-z0-9_-]+)*$/
const SECRET_EXEMPT = /\.(example|sample|template|dist|defaults?)$/
const LOCKFILES = new Set([
  'Cargo.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
  'uv.lock', 'poetry.lock', 'Pipfile.lock', 'flake.lock', 'Gemfile.lock',
  'composer.lock', 'go.sum', 'gradle.lockfile', 'pubspec.lock',
])
const BUILD_DIR = /(^|\/)(target|node_modules|dist|build|out|\.next|\.nuxt|\.venv|venv|__pycache__|\.tox|coverage|vendor)\//

const deny = (reason) => {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
      },
    }),
  )
  process.exit(0)
}

let raw = ''
process.stdin.on('data', (c) => (raw += c))
process.stdin.on('end', () => {
  let file = ''
  try {
    file = JSON.parse(raw)?.tool_input?.file_path || ''
  } catch {
    process.exit(0) // unparseable input is the harness's problem, not a policy breach
  }
  if (!file) process.exit(0)

  const base = file.split('/').pop()

  if (SECRET.test(file) && !SECRET_EXEMPT.test(file)) {
    deny(
      `flow: ${base} holds real credentials, and anything written there is one \`git add -A\` ` +
        'away from being in history forever. Put the key in your shell or a secret store and ' +
        `read it from the environment. Documenting a variable instead? Edit ${base}.example.`,
    )
  }

  if (LOCKFILES.has(base)) {
    deny(
      `flow: ${base} is generated by a resolver from a manifest, not written by hand. Change ` +
        'the manifest and re-run the resolver, so the lockfile and the manifest agree. If you ' +
        'are resolving a merge conflict, take one side whole and re-resolve.',
    )
  }

  if (BUILD_DIR.test(file)) {
    deny(
      `flow: ${file} is inside a build output directory — the next build overwrites it. If this ` +
        'is not a path bug, the change belongs in the source that generates this file.',
    )
  }

  process.exit(0)
})
