// Harness-neutral policy for flow's protected-file, registry-publication and merge guards.
// Policy takes a path or a command and returns a reason or null; the adapters in
// hooks/scripts/ own the wire formats and each host's answer.
//
// A cooperative guardrail, not a security boundary. Each guard stops the ordinary mistake,
// and a model at the same uid can reach the same effect through a command none of this reads.
// Over-matching costs one rephrase, so the reading below is regex over shell text, not a
// shell parser: a string built to look like a quote or a heredoc can hide a command from it.

import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SECRET = /(^|\/)\.env(\.[A-Za-z0-9_-]+)*$/
const SECRET_EXEMPT = /\.(example|sample|template|dist|defaults?)$/
const LOCKFILES = new Set([
  'Cargo.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
  'uv.lock', 'poetry.lock', 'Pipfile.lock', 'flake.lock', 'Gemfile.lock',
  'composer.lock', 'go.sum', 'gradle.lockfile', 'pubspec.lock',
])
const BUILD_DIR = /(^|\/)(target|node_modules|dist|build|out|\.next|\.nuxt|\.venv|venv|__pycache__|\.tox|coverage|vendor)\//

export function protectedFileReason(file) {
  const base = String(file).split('/').pop()

  if (SECRET.test(file) && !SECRET_EXEMPT.test(file)) {
    return `flow: ${base} holds real credentials, and anything written there is one \`git add -A\` ` +
      'away from being in history forever. Put the key in your shell or a secret store and ' +
      `read it from the environment. Documenting a variable instead? Edit ${base}.example.`
  }

  if (/(^|\/)\.flow\/managed$/.test(file)) {
    return 'flow: .flow/managed is the committed marker that opts this repository into flow\'s merge ' +
      'guardrail, the one that routes every pull request merge through scripts/land-merge.mjs instead of a raw ' +
      'merge command. A session that could edit or delete it could opt the repository out of ' +
      'its own guardrail, so this file is changed by a human commit, not by a tool call.'
  }

  if (LOCKFILES.has(base)) {
    return `flow: ${base} is generated by a resolver from a manifest, not written by hand. Change ` +
      'the manifest and re-run the resolver, so the lockfile and the manifest agree. If you ' +
      'are resolving a merge conflict, take one side whole and re-resolve.'
  }

  if (BUILD_DIR.test(file)) {
    return `flow: ${file} is inside a build output directory, and the next build overwrites it. If this ` +
      'is not a path bug, the change belongs in the source that generates this file.'
  }

  return null
}

// ------------------------------------------------------------------- reading a command
//
// Prose about an operation is not the operation. A heredoc body, a single-quoted string and a
// double-quoted string are text handed to some other command (a commit message, a PR comment,
// a gripe), so each one is masked before a rule reads the command.
//
// The exception is text a shell will run. In a segment that hands a string to `sh -c` (or bash,
// zsh, ksh, dash), to `eval`, or a heredoc to a shell's stdin, every literal is read again as a
// command of its own, with its own prose masked the same way, so `bash -lc 'gh pr merge 12'`
// merges and `bash -c "git commit -m 'about npm publish'"` still publishes nothing. A literal
// that is only an argument beside such a string is read as a command too; that over-match costs
// one rephrase. A shell fed through a pipe is not followed.
//
// A heredoc's body is the lines after its opener, so the rest of the opener line stays live:
// `cat <<'G' && git push --force` still pushes. A backslash-newline is one command, and only an
// odd run of backslashes escapes the newline. The `&` in a fd redirect is not the separator, so
// `npm publish 2>&1 --dry-run` stays one segment.
const HEREDOC = /(?<!<)<<(?!<)-?[ \t]*(['"]?)([\w-]+)\1([^\n]*)\n([\s\S]*?)^[ \t]*\2(?=[ \t)]*$)/gm
const CONTINUATION = /(?<!\\)((?:\\\\)*)\\\r?\n/g
const LITERAL = /(?<!\\)'[^']*'|(?<!\\)"(?:\\[\s\S]|[^"\\])*"/g
const FD_REDIRECT = /\d*>&\d*|&>>?/g
const SEPARATOR = /&&|\|\||[;&|\n]/
const PLACEHOLDER = /\0(\d+)\0/g
// Read on a segment whose literals are still placeholders: a shell given -c (alone or in a flag
// cluster, after any options), a shell whose next word is a literal (a heredoc on its stdin), or
// eval.
const RUNS_TEXT = /(?:^|\s)(?:\S*\/)?(?:sh|bash|zsh|ksh|dash)(?:\s+--?[A-Za-z][\w-]*)*?(?:\s+-[A-Za-z]*c[A-Za-z]*(?:\s|$)|\s*\0)|(?:^|\s)eval(?:\s|$)/
const NESTING = 4

// Every literal becomes a numbered placeholder, so the bare and the open reading of a command
// split into the same segments by construction.
function mask(command) {
  const literals = []
  const hold = (text) => `\0${literals.push(text) - 1}\0`
  const text = String(command)
    .replace(/\0/g, '')
    .replace(HEREDOC, (_m, _q, _d, rest, body) => `${hold(body)}${rest}`)
    .replace(CONTINUATION, '$1 ')
    .replace(LITERAL, (literal) => hold(literal.slice(1, -1)))
    .replace(FD_REDIRECT, ' ')
  return { text, literals }
}

// Each shell segment twice: `bare` with literals blanked, `open` with their text restored. A
// segment that runs its literals as commands is followed by their segments, read the same way.
function segments(command, depth = 0) {
  const { text, literals } = mask(command)
  return text.split(SEPARATOR).flatMap((segment) => {
    const own = {
      bare: segment.replace(PLACEHOLDER, ' '),
      open: segment.replace(PLACEHOLDER, (_m, i) => ` ${literals[i]} `),
    }
    if (depth >= NESTING || !RUNS_TEXT.test(segment)) return [own]
    return [own, ...[...segment.matchAll(PLACEHOLDER)].flatMap(([, i]) => segments(literals[i], depth + 1))]
  })
}

/**
 * The command with every heredoc body and quoted string blanked, one segment per `;`-joined
 * part, and the text a shell in it would run read the same way and appended as further parts.
 */
export const stripLiterals = (command) => segments(command).map(({ bare }) => bare).join(' ; ')

// -------------------------------------------------------------------- registry publication
//
// These registries have no real undo, so a publication needs a human. A dry run exempts only
// its own segment: a global check would let `cargo publish --dry-run && cargo publish` through.
const REGISTRIES = [
  [/\bcargo\s+publish\b/, 'crates.io', 'crates.io has no unpublish at all'],
  [/\b(?:npm|pnpm|yarn\s+npm)\s+publish\b/, 'npm', 'npm unpublish is a 72-hour window, and only while nothing depends on it'],
  [/\bgem\s+push\b/, 'RubyGems', 'a yanked gem keeps its version number forever'],
  [/\b(?:twine\s+upload|poetry\s+publish|uv\s+publish)\b/, 'PyPI', 'PyPI will not let you reuse a version number, even after deletion'],
]
const DRY_RUN = /(?:^|\s)--dry-run(?=\s|$)/

/** Why this command needs a human before it runs, or null when it publishes nothing. */
export function publishReason(command) {
  for (const { bare } of segments(command)) {
    if (DRY_RUN.test(bare)) continue
    const hit = REGISTRIES.find(([re]) => re.test(bare))
    if (hit) {
      return `This publishes to ${hit[1]}, which you cannot take back, because ${hit[2]}. ` +
        'Confirm the version number and the contents are what you mean to ship.'
    }
  }
  return null
}

// ---------------------------------------------------------------------- the merge tripwire
//
// A repository opts in by committing `.flow/managed`. There, every merge command these regexes
// recognize is denied, and the denial names scripts/land-merge.mjs, which derives the repository
// from origin, runs every land gate itself against GitHub, and merges only when none stops it. The
// human asking to land is the authorization; the deny only keeps the merge on the path that
// verifies what it merges. Elsewhere nothing here gates a merge, and scheduled jobs merge nothing,
// executor included.
//
// The one hard requirement is that the tripwire never matches the executor's own invocation.
// Each regex needs a `gh` command word in the bare segment. The executor's argv is a pull request
// number, a SHA and any `--accept-flake <check>:<test>` values, so it has none: a check name with
// a space in it is quoted, and the bare reading blanks quoted text. The REST path and the GraphQL
// mutation are nearly always quoted, so those two read the segment's open text once its bare text
// is a `gh api` call.
const GH = String.raw`(?:^|\s)(?:\S*/)?gh\s+(?:\S+\s+)*?`
const PR_MERGE = new RegExp(`${GH}pr\\s+merge(?:\\s|$)`)
const GH_API = new RegExp(`${GH}api(?:\\s|$)`)
const REST_MERGE = /\/merges?\b/
const GRAPHQL_MERGE = /\bmergePullRequest\b/

function mergeShapes(command) {
  const found = new Set()
  for (const { bare, open } of segments(command)) {
    if (PR_MERGE.test(bare)) found.add('it runs `gh pr merge`')
    if (!GH_API.test(bare)) continue
    if (REST_MERGE.test(open)) found.add('it calls a GitHub merge endpoint through `gh api`')
    if (GRAPHQL_MERGE.test(open)) found.add('it sends a mergePullRequest GraphQL mutation')
  }
  return [...found]
}

const EXECUTOR = join(dirname(dirname(fileURLToPath(import.meta.url))), 'scripts', 'land-merge.mjs')

// The marker committed at HEAD is the opt-in, so a deleted working-tree copy does not opt out
// and an untracked one does not opt in. `ls-tree` prints the path when it is committed and
// nothing when it is not, both on exit 0, so empty output is a real "unmanaged". Any failure (no
// repository, an unborn HEAD, a git that does not answer within 2 s) reads as managed: a false
// deny costs the human a look, a false allow a merge that skipped the executor. Only a
// merge-shaped command pays for this read.
function isManagedRepo(cwd) {
  try {
    return execFileSync('git', ['-C', cwd, 'ls-tree', '--full-tree', '--name-only', 'HEAD', '--', '.flow/managed'], {
      encoding: 'utf8', timeout: 2000, stdio: ['ignore', 'pipe', 'ignore'],
    }).trim() !== ''
  } catch {
    return true
  }
}

/**
 * The reason this command must not run as written, or null. One decision, both hosts.
 *
 * `cwd` is the session's directory as the hook reported it, and `env` is the hook process's own
 * environment: the cron session's when a scheduled job launched it, so a command that strips
 * FLOW_CRON_JOB off its own child is still denied here.
 *
 * @param {{ command: unknown, cwd?: unknown, env?: Record<string, string | undefined> }} call
 * @returns {string | null}
 */
export function mergeDenialFor({ command, cwd, env = {} }) {
  if (typeof command !== 'string') return null
  const shapes = mergeShapes(command)

  if (env.FLOW_CRON_JOB && (shapes.length > 0 || /\bland-merge\.mjs\b/.test(command))) {
    const what = shapes.length > 0 ? `this looks like a pull request merge (${shapes.join('; ')})` : 'this runs flow\'s merge executor'
    return `flow: ${what}, and scheduled jobs do not merge anything. FLOW_CRON_JOB is set, which means ` +
      'nobody is watching this run. Leave the pull request for a human session to land.'
  }

  if (shapes.length === 0) return null
  if (!isManagedRepo(typeof cwd === 'string' && cwd !== '' ? cwd : process.cwd())) return null

  return `flow: this looks like a pull request merge (${shapes.join('; ')}), and this repository opts into flow's ` +
    'merge guardrail with a committed .flow/managed file. Merges here run through the executor: ' +
    `\`node "${EXECUTOR}" <pr-number> <expected-head-sha> [--accept-flake <check>:<test>]...\`, with the full ` +
    '40-character head SHA you read from `gh pr view`. It derives the repository from origin and runs the land ' +
    'gates itself. It refuses a pull request that is not open, is a draft, has moved off that head, is not based on ' +
    'the default branch or is behind it, or has auto-merge or a merge queue armed. It also refuses one with a ' +
    'pending, failed or unknown check that the base branch\'s known flakes do not excuse, or with an unresolved ' +
    'review thread. It merges with --match-head-commit and confirms by re-reading the pull request. Run it when ' +
    'the human has asked to land this pull request, and act on each stop it reports.'
}
