// Harness-neutral policy for flow's protected-file and public-registry guards.
// Adapters own wire formats: policy receives commands or paths and returns a reason.

const SECRET = /(^|\/)\.env(\.[A-Za-z0-9_-]+)*$/
const SECRET_EXEMPT = /\.(example|sample|template|dist|defaults?)$/
const LOCKFILES = new Set([
  'Cargo.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lockb',
  'uv.lock', 'poetry.lock', 'Pipfile.lock', 'flake.lock', 'Gemfile.lock',
  'composer.lock', 'go.sum', 'gradle.lockfile', 'pubspec.lock',
])
const BUILD_DIR = /(^|\/)(target|node_modules|dist|build|out|\.next|\.nuxt|\.venv|venv|__pycache__|\.tox|coverage|vendor)\//

const PUBLISH = [
  [/\bcargo\s+publish\b/, 'crates.io', 'crates.io has no unpublish at all'],
  [/\bnpm\s+publish\b/, 'npm', 'npm unpublish is a 72-hour window, and only while nothing depends on it'],
  [/\bpnpm\s+publish\b/, 'npm', 'npm unpublish is a 72-hour window, and only while nothing depends on it'],
  [/\byarn\s+npm\s+publish\b/, 'npm', 'npm unpublish is a 72-hour window, and only while nothing depends on it'],
  [/\bgem\s+push\b/, 'RubyGems', 'a yanked gem keeps its version number forever'],
  [/\btwine\s+upload\b/, 'PyPI', 'PyPI will not let you reuse a version number, even after deletion'],
  [/\bpoetry\s+publish\b/, 'PyPI', 'PyPI will not let you reuse a version number, even after deletion'],
  [/\buv\s+publish\b/, 'PyPI', 'PyPI will not let you reuse a version number, even after deletion'],
]

export function protectedFileReason(file) {
  const base = String(file).split('/').pop()

  if (SECRET.test(file) && !SECRET_EXEMPT.test(file)) {
    return `flow: ${base} holds real credentials, and anything written there is one \`git add -A\` ` +
      'away from being in history forever. Put the key in your shell or a secret store and ' +
      `read it from the environment. Documenting a variable instead? Edit ${base}.example.`
  }

  if (LOCKFILES.has(base)) {
    return `flow: ${base} is generated by a resolver from a manifest, not written by hand. Change ` +
      'the manifest and re-run the resolver, so the lockfile and the manifest agree. If you ' +
      'are resolving a merge conflict, take one side whole and re-resolve.'
  }

  if (BUILD_DIR.test(file)) {
    return `flow: ${file} is inside a build output directory - the next build overwrites it. If this ` +
      'is not a path bug, the change belongs in the source that generates this file.'
  }

  return null
}

export function publishReason(command) {
  // Prose about publishing is not publishing. This deliberately matches the existing
  // Claude guard: simple quoted literals are removed before policy sees the command.
  // A backslash continuation is the same command, and the `&` inside a fd redirect is
  // not the background separator - `npm publish \<newline> --dry-run` and
  // `npm publish 2>&1 --dry-run` must each keep their own exemption.
  const bare = String(command)
    .replace(/\\\r?\n/g, ' ')
    .replace(/'[^']*'/g, ' ')
    .replace(/"[^"]*"/g, ' ')
    .replace(/\d*>&\d*|&>>?/g, ' ')
  // A dry-run exempts only its shell segment. A global check lets
  // `cargo publish --dry-run && cargo publish` bypass the second, real publication.
  for (const segment of bare.split(/&&|\|\||[;&|\n]/)) {
    if (/--dry-run\b/.test(segment)) continue
    for (const [re, registry, why] of PUBLISH) {
      if (re.test(segment)) {
        return `This publishes to ${registry}, which you cannot take back - ${why}. ` +
          'Confirm the version number and the contents are what you mean to ship.'
      }
    }
  }
  return null
}

/** Extract every target path from Codex's apply_patch command envelope. */
export function applyPatchPaths(command) {
  const text = String(command)
  const lines = text.split('\n')
  const paths = []
  const begins = lines.filter((line) => line === '*** Begin Patch').length
  const ends = lines.filter((line) => line === '*** End Patch').length
  let malformed = begins !== 1 || ends !== 1 ||
    lines.indexOf('*** Begin Patch') >= lines.indexOf('*** End Patch')

  for (const line of lines) {
    const file = line.match(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/)
    const move = line.match(/^\*\*\* Move to: (.+)$/)
    if (file || move) {
      const path = (file || move)[1].trim()
      if (!path || path.includes('\0')) malformed = true
      else paths.push(path)
    } else if (/^\*\*\* .*(?:File|to):/.test(line)) {
      // A future or malformed target directive must not turn into an uninspected path.
      malformed = true
    }
  }

  if (paths.length === 0) malformed = true
  return { paths: [...new Set(paths)], complete: !malformed }
}

export const preToolDeny = (reason) => ({
  hookSpecificOutput: {
    hookEventName: 'PreToolUse',
    permissionDecision: 'deny',
    permissionDecisionReason: reason,
  },
})
